### ISSUE TITLE
change twitter handle name to "CoreOS Linux Version"

### ISSUE THREAD

**Issue by philips** [heqian/CoreOSVersion#1]
Hey, would y'all mind changing the Twitter handle to say "CoreOS Linux Version". The project is technically called "CoreOS Linux" today. CoreOS is the company name.

cc @crawford

**Comment by heqian** [comment]
No problem. Just done.
What would you recommend for the Twitter username? "CoreOSLinuxVersion" will be too long. Twitter won't accept the username change.
